version: "3"

services:

  webserver:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chatbot
      - word2vec
      - ontology
    #ports:
    #  - 80:80
    environment:
      - VIRTUAL_HOST=lipchat.mooo.com
    networks: 
      - lipchatnet

  chatbot:
    image: php:7-apache
    volumes:
      - ./lipchat-chatbot:/var/www/html/
    depends_on:
      - word2vec
      - ontology
    networks:
      - lipchatnet
      
  ontology:
    build: ./lipchat-ontologyreasoner
    networks:
      - lipchatnet
  
  word2vec:
    build: ./lipchat-word2vec
    networks:
      - lipchatnet

networks:
  lipchatnet:
    driver: bridge
